// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:774efb61-dd34-4cfa-8e22-54d3217889e1",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_IOX8ipuY4",
    "aws_user_pools_web_client_id": "4un3vcsps6a42bk0p4j58e98t3",
    "oauth": {},
    "aws_user_files_s3_bucket": "foam-turret-bolos-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
